#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#


obj-$(CONFIG_MCD_PANEL) += timenval.o \
				panel.o \
				panel_bl.o \
				dimming.o \
				panel_drv.o \
				panel_irc.o

obj-$(CONFIG_PANEL_DISPLAY_MODE) += panel_modes.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS) += sysfs.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie.o
obj-$(CONFIG_PANEL_DEBUG) += panel_debug.o
obj-$(CONFIG_EXTEND_LIVE_CLOCK) += aod/aod_drv.o
obj-$(CONFIG_DYNAMIC_MIPI) += dynamic_mipi/dynamic_mipi.o
obj-$(CONFIG_SUPPORT_MAFPC) += mafpc/mafpc_drv.o
obj-$(CONFIG_PANEL_NOTIFY) += panel_notify.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_EXYNOS_DECON_LCD_COPR) += copr.o
obj-$(CONFIG_SUPPORT_POC_SPI) += panel_poc.o panel_spi.o
obj-$(CONFIG_SUPPORT_DISPLAY_PROFILER) += \
	display_profiler/display_profiler.o \
	display_profiler/maskgen.o

obj-$(CONFIG_DISPLAY_S6E36W4X01) += s6e36w4x01/
obj-$(CONFIG_DISPLAY_S6E36W5X01) += s6e36w5x01/
obj-$(CONFIG_DISPLAY_RM69091) += rm69091/

