/*****************************************************************************
 *
 * Copyright (c) 2012 - 2022 Samsung Electronics Co., Ltd. All rights reserved
 *
 *****************************************************************************/
#ifndef __SLSI_CHANNELS_H__
#define __SLSI_CHANNELS_H__

#define SLSI_NUM_2P4GHZ_CHANNELS 14
#ifdef CONFIG_SCSC_UNII4
#define SLSI_NUM_5GHZ_CHANNELS 28
#else
#define SLSI_NUM_5GHZ_CHANNELS 25
#endif

#define SLSI_2P4GHZ_MIN_FREQ 2412
#define SLSI_2P4GHZ_MAX_FREQ 2484
#define SLSI_5GHZ_MIN_FREQ 5180
#ifdef CONFIG_SCSC_UNII4
#define SLSI_5GHZ_MAX_FREQ 5885
#define SLSI_5GHZ_LAST_CHAN 177
#else
#define SLSI_5GHZ_MAX_FREQ 5825
#define SLSI_5GHZ_LAST_CHAN 165
#endif

#define SLSI_6GHZ_LAST_CHAN 233
#define SLSI_NUM_6GHZ_CHANNELS 59
#define SLSI_NUM_6GHZ_UNII5_6 29

#define SLSI_6GHZ_MIN_FREQ 5955
#define SLSI_6GHZ_MAX_FREQ 7115

#ifdef CONFIG_SCSC_WLAN_SUPPORT_6G
#define SLSI_MAX_CHAN_VALUE_ACS (SLSI_NUM_2P4GHZ_CHANNELS + SLSI_NUM_5GHZ_CHANNELS + SLSI_NUM_6GHZ_CHANNELS)
#else
#define SLSI_MAX_CHAN_VALUE_ACS (SLSI_NUM_2P4GHZ_CHANNELS + SLSI_NUM_5GHZ_CHANNELS)
#endif

/* ISM(2.4GHz), UNII1, UNII2a, UNII2c, UNII3, UNII4, UNII5(6GHz)*/
#define SLSI_MAX_SUB_BANDS 7
#ifdef CONFIG_SCSC_WLAN_WIFI_SHARING
#define SLSI_2P4GHZ_CHANNEL_ONE 2412
#endif
#ifdef CONFIG_SCSC_WLAN_SUPPORT_6G
#define SLSI_MAX_SUPPORTED_CHANNELS_NUM (SLSI_NUM_2P4GHZ_CHANNELS + SLSI_NUM_5GHZ_CHANNELS + SLSI_NUM_6GHZ_CHANNELS)
#else
#define SLSI_MAX_SUPPORTED_CHANNELS_NUM (SLSI_NUM_2P4GHZ_CHANNELS + SLSI_NUM_5GHZ_CHANNELS)
#endif

#define SLSI_ROAMING_CHANNELS_MAX SLSI_MAX_SUPPORTED_CHANNELS_NUM

#endif
